DECLARE @Parameters AS XML = '
<PutRequest>
  <SalesOrders>
    <SalesOrder Id="1">
      <EcatOrderNumber>001-AddressChanges</EcatOrderNumber>
      <RetrievedDateTime>2023-06-19 14:00:00</RetrievedDateTime>
      <OrderType>Confirmed</OrderType>
      <RawDocumentText><![CDATA[{
    "gwc_split_order": "false",
    "additional_fields": {
        "shippingterms": "Prepaid Freight",
        "billto_shipmentrequest": "As Available",
        "billto_addresstype": "Commercial",
        "billto_deliveryinfo": "214-636-3196",
        "order_origin" : "Austin",
        "billto_deliverytype": "Standard-"
    },
    "bill_to_address_changed": null,
    "ship_to_address_changed": null,
    "bill_to_line1": "4007 Timberwood Dr",
    "bill_to_line2": "---",
    "bill_to_city": "Nacogdoches",
    "bill_to_company_name": "Customer",
    "bill_to_country": "USA",
    "bill_to_postal_code": "75965",
    "bill_to_state": "TX",
    "buyer_first_name": "Justin",
    "buyer_last_name": "Pope",
    "customer_email_address": "pope2014@gmail.com",
    "customer_number": "1260704",
    "customer_phone_number": "214-636-3196",
    "customer_po_number": "01addresstest",
    "discount_amount_cents": null,
    "discount_percent": null,
    "ecat_version": null,
    "id": 9999999,
    "is_exported": false,
    "is_submitted": true,
    "notes": "",
    "order_items": [
        {
            "gwc_stock_code_override": "(none)",
            "discount_notes": [],
            "has_discount": false,
            "option_notes": [],
            "calculated_price": 1294.0,
            "line_notes": [],
            "extended_price": 1294.0,
            "extended_product_volume": 29.87,
            "description": "Ezekiel Cabinet- Dark",
            "item_number": "SCH-169260",
            "item_price": 1294.0,
            "matrix_option_item_code": "",
            "options": [],
            "quantity": 1,
            "units_per_carton": null,
            "custom_fields": {
                "i.qty_available": 91,
                "i.qty_in_transit": 95,
                "i.qty_on_hand": 95,
                "i.qty_in_showroom": 0,
                "StockEta": "Oct 5, 2022",
                "Introduction": "HP Fall 2020",
                "product_dimensions_in": "46 W 18 D 43 H",
                "shipping_weight": 203.19,
                "minimum_order": 1,
                "CountryOfOrigin": "Indonesia",
                "EstimatedFreightCost": "0",
                "AvailableAtlantaShowroom": "1",
                "AvailableDallasShowroom": "1",
                "AvailableHighPointShowroom": "1",
                "AvailableLasVegasShowroom": "0",
                "ProductStatus": "Current",
                "AvailableAtlantaStore": "0",
                "AvailableCharlotteStore": "0",
                "AvailableChestnutHillStore": "0",
                "AvailableNashvilleStore": "0",
                "AvailablePelhamOutlet": "0",
                "AvailableRaleighStore": "0",
                "AvailableRichmondStore": "0",
                "AvailableSanAntonioStore": "1",
                "AvailablePelhamShowroom": "0",
                "AvailableStLouisStore": "0",
                "AvailableJacksonvilleStore": "0",
                "AvailableWinterParkStore": "0",
                "BuildStockCodeType": "Gabby",
                "CarrierType": "Common",
                "CreateStockCodeEligible": "false",
                "CreateStockCodeType": "Gabby",
                "FrameType": "Cabinets",
                "Essential": "N",
                "WhiteLabel": "N",
                "AvailableAustinStore": "1",
                "AvailableAtlantaOutlet": "0",
                "AvailableWH15": "0",
                "AvailableWH16": "0"
            },
            "upc_value": null,
            "upc_type": null
        }
    ],
    "order_number": "001-AddressChanges",
    "order_source": "server",
    "order_type": "Confirmed",
    "organization_id": 69,
    "price_level": "4",
    "rep_email": null,
    "rep_first_name": null,
    "rep_last_name": null,
    "rep_number": "LWE",
    "rep_phone": null,
    "ship_date": null,
    "cancel_date": null,
    "ship_to_line1": "4007 Timberwood Dr",
    "ship_to_line2": "---",
    "ship_to_city": "Nacogdoches",
    "ship_to_code": "",
    "ship_to_company_name": "Customer",
    "ship_to_country": "USA",
    "ship_to_postal_code": "75965",
    "ship_to_state": "TX",
    "submit_date": "2023-06-19T13:59:00Z",
    "surcharges": [],
    "tag_for": "",
    "total_cents": 129400,
    "total_product_volume": 29.87,
    "uuid": "7da05a90-71fd-46cb-88e6-a67f058a4acd",
    "local_customer_code": null,
    "bill_to_line3": "Nacogdoches, TX",
    "ship_to_line3": null,
    "ship_to_email_address": null,
    "ship_to_phone_number": null,
    "payment_information": {}
}]]></RawDocumentText>
      <DocumentStatus>Staged</DocumentStatus>
      <ToBeProcessed>true</ToBeProcessed>
    </SalesOrder>
    <SalesOrder Id="2">
      <EcatOrderNumber>002-AddressChanges</EcatOrderNumber>
      <RetrievedDateTime>2023-06-19 14:00:00</RetrievedDateTime>
      <OrderType>Confirmed</OrderType>
      <RawDocumentText><![CDATA[{
    "gwc_split_order": "false",
    "additional_fields": {
        "shipment_preference": null,
        "shippingterms": "Prepaid Freight",
        "billto_shipmentrequest": "Complete",
        "billto_addresstype": "Commercial",
        "shipping_method": null,
        "order_origin" : "Atlanta Store",
        "billto_deliverytype": "Standard"
    },
    "bill_to_address_changed": false,
    "ship_to_address_changed": false,
    "bill_to_line1": "5223 Orient Rd",
    "bill_to_line2": "---",
    "bill_to_city": "Tampa",
    "bill_to_company_name": "Customer",
    "bill_to_country": null,
    "bill_to_postal_code": "33610",
    "bill_to_state": "FL",
    "buyer_first_name": null,
    "buyer_last_name": null,
    "customer_email_address": "ann@aemonroe.com",
    "customer_number": "1260705",
    "customer_phone_number": "866-388-4263",
    "customer_po_number": "02addresstest",
    "discount_amount_cents": null,
    "discount_percent": null,
    "ecat_version": "2021.5.0.9",
    "id": 1046363,
    "is_exported": false,
    "is_submitted": true,
    "notes": "",
    "order_items": [
        {
            "gwc_stock_code_override": "(none)",
            "discount_notes": [],
            "has_discount": false,
            "option_notes": [],
            "calculated_price": 731.0,
            "line_notes": [],
            "extended_price": 4386.0,
            "extended_product_volume": 186.0,
            "description": "Rustic Woven Lounge Chair Black Walnut",
            "item_number": "37472",
            "item_price": 731.0,
            "matrix_option_item_code": null,
            "options": [],
            "quantity": 6,
            "units_per_carton": 1,
            "custom_fields": {
                "i.qty_available": 79,
                "i.qty_in_transit": 79,
                "i.qty_on_hand": 79,
                "i.qty_in_showroom": 0,
                "StockEta": "Oct 5, 2022",
                "ProductStatus": "Current",
                "FrameType": "Lounge Chair",
                "FinishName": "Black Walnut",
                "product_dimensions_in": "37.25 W 38 D 30.75 H 23 Arm H 11.25 Seat H",
                "plist_description": "Black Walnut",
                "CarrierType": "Common",
                "Essential": "N",
                "WhiteLabel": "N",
                "AvailableAtlantaStore": "3",
                "AvailableCharlotteStore": "0",
                "AvailableChestnutHillStore": "0",
                "AvailableJacksonvilleStore": "0",
                "AvailableNashvilleStore": "0",
                "AvailablePelhamOutlet": "2",
                "AvailableRaleighStore": "0",
                "AvailableRichmondStore": "0",
                "AvailableSanAntonioStore": "0",
                "AvailablePelhamShowroom": "0",
                "AvailableStLouisStore": "0",
                "AvailableWinterParkStore": "0",
                "AvailableAtlantaShowroom": "0",
                "AvailableDallasShowroom": "0",
                "AvailableHighPointShowroom": "1",
                "AvailableLasVegasShowroom": "0",
                "BuildStockCodeType": "(none)",
                "CountryOfOrigin": "Indonesia",
                "CreateStockCodeEligible": "false",
                "CreateStockCodeType": "(none)",
                "shipping_weight": 79.25,
                "UmbrellaHole": "N",
                "AvailableAustinStore": "0",
                "AvailableAtlantaOutlet": "1",
                "AvailableWH15": "0",
                "AvailableWH16": "0"
            },
            "upc_value": null,
            "upc_type": null
        }
    ],
    "order_number": "002-AddressChanges",
    "order_source": "ipad",
    "order_type": "Confirmed",
    "organization_id": 69,
    "price_level": "4",
    "rep_email": "SeanB@summerclassics.com",
    "rep_first_name": "Sean",
    "rep_last_name": "Banda",
    "rep_number": "CG",
    "rep_phone": "",
    "ship_date": null,
    "cancel_date": null,
    "ship_to_line1": "5223 Orient Rd",
    "ship_to_line2": null,
    "ship_to_city": "Tampa",
    "ship_to_code": "",
    "ship_to_company_name": "Seminole Hard Rock Hotel & Casino Tampa",
    "ship_to_country": "USA",
    "ship_to_postal_code": "50018",
    "ship_to_state": "FL",
    "submit_date": "2023-06-19T13:59:00Z",
    "surcharges": [],
    "tag_for": "",
    "total_cents": 438600,
    "total_product_volume": 186.0,
    "uuid": "CDB0F375-9446-4CE2-A802-320260A51E82",
    "local_customer_code": null,
    "bill_to_line3": "Tampa, FL",
    "ship_to_line3": null,
    "ship_to_email_address": null,
    "ship_to_phone_number": null,
    "payment_information": {}
}]]></RawDocumentText>
      <DocumentStatus>Staged</DocumentStatus>
      <ToBeProcessed>true</ToBeProcessed>
    </SalesOrder>
  </SalesOrders>
</PutRequest>
';

EXECUTE SysproDocument.ESS.usp_Stage_SalesOrder_Raw_Put @Parameters;