Select 
	'Gabby' as DEPARTMENT
	,RowId
	,UserGroup
	,Username
	,FirstName
	,LastName
	,Email
	,Phone
	,TerritoryCodes
	,CreateDateTime
	,LastLoginDateTimeUtc
	,eCatVersion
	,iOSVersion
	,iPadModel
	,IsAdmin
	,Disabled
	,CustomerNumber
	,ApplicationCity
	,ApplicationCompanyEmail
	,ApplicationCompanyName
	,ApplicationCompanyPhone
	,ApplicationCompanyWebsite
	,ApplicationCountry
	,ApplicationCustomerNumber
	,ApplicationEmail
	,ApplicationFirstName
	,ApplicationLastName
	,ApplicationPhone
	,ApplicationState
	,ApplicationStreetAddress
	,ApplicationZip
	,CompanyName
	,CompanyWebsite
	,CompanyEmail
	,CompanyPhone
	,LastEcatOnlineLoginDateUtc
	,CustomerCode
	,CustomerName
	,CustomerAddress3
	,CustomerCity
	,CustomerState
	,CustomerZip
	,CustomerPhone
	,CustomerDefaultPriceCode
	,CustomerTerritoryCodes
	,CustomerAddress1
	,CustomerAddress2 
from Ecat.Export.Data_Gabby_User

UNION
Select 
	'SCC'
	,RowId
	,UserGroup
	,Username
	,FirstName
	,LastName
	,Email
	,Phone
	,TerritoryCodes
	,CreateDateTime
	,LastLoginDateTimeUtc
	,eCatVersion
	,iOSVersion
	,iPadModel
	,IsAdmin
	,Disabled
	,CustomerNumber
	,ApplicationCity
	,ApplicationCompanyEmail
	,ApplicationCompanyName
	,ApplicationCompanyPhone
	,ApplicationCompanyWebsite
	,ApplicationCountry
	,ApplicationCustomerNumber
	,ApplicationEmail
	,ApplicationFirstName
	,ApplicationLastName
	,ApplicationPhone
	,ApplicationState
	,ApplicationStreetAddress
	,ApplicationZip
	,CompanyName
	,CompanyWebsite
	,CompanyEmail
	,CompanyPhone
	,LastEcatOnlineLoginDateUtc
	,CustomerCode
	,CustomerName
	,CustomerAddress3
	,CustomerCity
	,CustomerState
	,CustomerZip
	,CustomerPhone
	,CustomerDefaultPriceCode
	,CustomerTerritoryCodes
	,CustomerAddress1
	,CustomerAddress2 
	from Ecat.Export.Data_SummerClassics_Contract_User
Union
Select 
	'SCW'
	,RowId
	,UserGroup
	,Username
	,FirstName
	,LastName
	,Email
	,Phone
	,TerritoryCodes
	,CreateDateTime
	,LastLoginDateTimeUtc
	,eCatVersion
	,iOSVersion
	,iPadModel
	,IsAdmin
	,Disabled
	,CustomerNumber
	,ApplicationCity
	,ApplicationCompanyEmail
	,ApplicationCompanyName
	,ApplicationCompanyPhone
	,ApplicationCompanyWebsite
	,ApplicationCountry
	,ApplicationCustomerNumber
	,ApplicationEmail
	,ApplicationFirstName
	,ApplicationLastName
	,ApplicationPhone
	,ApplicationState
	,ApplicationStreetAddress
	,ApplicationZip
	,CompanyName
	,CompanyWebsite
	,CompanyEmail
	,CompanyPhone
	,LastEcatOnlineLoginDateUtc
	,CustomerCode
	,CustomerName
	,CustomerAddress3
	,CustomerCity
	,CustomerState
	,CustomerZip
	,CustomerPhone
	,CustomerDefaultPriceCode
	,CustomerTerritoryCodes
	,CustomerAddress1
	,CustomerAddress2 from  Ecat.Export.Data_SummerClassics_Wholesale_User