use [SysproCompany100]
go

insert into [dbo].[InvMaster+] (	[StockCode], 
									[AvailableToday], 
									[AvailableIn15Days], 
									[AvailableIn30Days], 
									[CarrierType], 
									[CoaRequired], 
									[CommodityClass], 
									[CompSchDefault], 
									[CushStyle], 
									[CushFabric], 
									[CushCustomCompont],
									[CushionEmbroidery],
									[DefaultRoute],
									[DiscontinuedDate],
									[Essential],
									[IncludeAvailReport], 
									[IncludeCycleCount], 
									[IncludeSaleReport], 
									[LifoPool], 
									[LoadingFactor], 
									[LookAheadWindow], 
									[NextAvailableDate], 
									[NmfcCode], 
									[OrderEntryNote], 
									[ProductCategory], 
									[ProductGrouping], 
									[ProductStatus], 
									[ProductType], 
									[ProposedCost], 
									[PurchasingGroup],
									[QaInsReason],
									[SpecialNotes],
									[Units], 
									[WarehouseProgram], 
									[WhiteLabel], 
									[NewCategory], 
									[SerialRequired], 
									[Style], 
									[Size1], 
									[CurrentLot], 
									[UnitSales3Months], 
									[UnitSales6Months], 
									[UnitSales12Months], 
									[ProductNumber], 
									[BodyFabric], 
									[CushionFillType], 
									[CushionConfig], 
									[NailheadFinish], 
									[NailheadPattern], 
									[Finish], 
									[CustomWidth], 
									[CustomDepth], 
									[CustomArm], 
									[CustomBack], 
									[CustomBase], 
									[OutboundVolume], 
									[UmbHoleDiameter], 
									[PriceMultiplierCat], 
									[CustomStockCode], 
									[WindowBoxFabric], 
									[SkirtTapingFabric], 
									[BodyWelt], 
									[ExtWarrantyType], 
									[PimDepartment], 
									[PimCategory], 
									[PimSubcategory], 
									[PimType], 
									[PillowFabric], 
									[PillowTrim], 
									[PillowTreatment], 
									[SkirtTaping], 
									[SectionalNotches], 
									[ContrastWeltFabric], 
									[ContrastWeltLoc], 
									[ContrastFabric], 
									[ContrastFabricLoc], 
									[PimTypeId], 
									[ContrastInsideFab], 
									[CushThreadColor], 
									[OutboundInspection], 
									[ExcessInventory], 
									[LabelColor] 
								)
	select
		'JKP-0001'	as [StockCode], 
		'T1-1'		as [AvailableToday], 
		'T1-1'		as [AvailableIn15Days], 
		'T1-1'		as [AvailableIn30Days], 
		'T1-1'		as [CarrierType], 
		'T1-1'		as [CoaRequired], 
		'T1-1'		as [CommodityClass], 
		'T1-1'		as [CompSchDefault], 
		'T1-1'		as [CushStyle], 
		'T1-1'		as [CushFabric], 
		'T1-1'		as [CushCustomCompont],
		'1'			as [CushionEmbroidery],
		'1'			as [DefaultRoute],
		getdate()	as [DiscontinuedDate],
		'1'			as [Essential],
		'1'			as [IncludeAvailReport], 
		'1'			as [IncludeCycleCount], 
		'1'			as [IncludeSaleReport], 
		'T1-1'		as [LifoPool], 
		1.1			as [LoadingFactor], 
		1.1			as [LookAheadWindow], 
		getdate()	as [NextAvailableDate], 
		'T1-1'		as [NmfcCode], 
		'T1-1'		as [OrderEntryNote], 
		'T1-1'		as [ProductCategory], 
		'T1-1'		as [ProductGrouping], 
		'1'			as [ProductStatus], 
		'T1-1'		as [ProductType], 
		1.1			as [ProposedCost], 
		'T1-1'		as [PurchasingGroup],
		'T1-1'		as [QaInsReason],
		'T1-1'		as [SpecialNotes],
		'1'			as [Units], 
		'1'			as [WarehouseProgram], 
		'1'			as [WhiteLabel],
		'T1-1'		as [NewCategory], 
		'T1-1'		as [SerialRequired], 
		'T1-1'		as [Style], 
		'T1-1'		as [Size1], 
		'T1-1'		as [CurrentLot], 
		1.1			as [UnitSales3Months], 
		1.1			as [UnitSales6Months], 
		1.1			as [UnitSales12Months], 
		'T1-1'		as [ProductNumber], 
		'T1-1'		as [BodyFabric], 
		'T1-1'		as [CushionFillType], 
		'T1-1'		as [CushionConfig], 
		'T1-1'		as [NailheadFinish], 
		'T1-1'		as [NailheadPattern], 
		'T1-1'		as [Finish], 
		1.1			as [CustomWidth], 
		1.1			as [CustomDepth], 
		'T1-1'		as [CustomArm], 
		'T1-1'		as [CustomBack], 
		'T1-1'		as [CustomBase], 
		1.1			as [OutboundVolume], 
		1.1			as [UmbHoleDiameter], 
		'T1-1'		as [PriceMultiplierCat], 
		'1'			as [CustomStockCode], 
		'T1-1'		as [WindowBoxFabric], 
		'T1-1'		as [SkirtTapingFabric], 
		'T1-1'		as [BodyWelt], 
		'T1-1'		as [ExtWarrantyType], 
		'T1-1'		as [PimDepartment], 
		'T1-1'		as [PimCategory], 
		'T1-1'		as [PimSubcategory], 
		'T1-1'		as [PimType], 
		'T1-1'		as [PillowFabric], 
		'T1-1'		as [PillowTrim], 
		'T1-1'		as [PillowTreatment], 
		'T1-1'		as [SkirtTaping], 
		'T1-1'		as [SectionalNotches], 
		'T1-1'		as [ContrastWeltFabric], 
		'T1-1'		as [ContrastWeltLoc], 
		'T1-1'		as [ContrastFabric], 
		'T1-1'		as [ContrastFabricLoc], 
		'T1-1'		as [PimTypeId], 
		'T1-1'		as [ContrastInsideFab], 
		'T1-1'		as [CushThreadColor], 
		'1'			as [OutboundInspection], 
		'1'			as [ExcessInventory], 
		'T1-1'		as [LabelColor] 
	union
	select
		'JKP-0002' as [StockCode], 
		'T2-1' as [AvailableToday], 
		'T2-1' as [AvailableIn15Days], 
		'T2-1' as [AvailableIn30Days], 
		'T2-1' as [CarrierType], 
		'T2-1' as [CoaRequired], 
		'T2-1' as [CommodityClass], 
		'T2-1' as [CompSchDefault], 
		'T2-1' as [CushStyle], 
		'T2-1' as [CushFabric], 
		'T2-1' as [CushCustomCompont],
		'1' as [CushionEmbroidery],
		'1' as [DefaultRoute],
		getdate() as [DiscontinuedDate],
		'1' as [Essential],
		'1' as [IncludeAvailReport], 
		'1' as [IncludeCycleCount], 
		'1' as [IncludeSaleReport], 
		'T2-1' as [LifoPool], 
		1.1 as [LoadingFactor], 
		1.1 as [LookAheadWindow], 
		getdate() as [NextAvailableDate], 
		'T2-1' as [NmfcCode], 
		'T2-1' as [OrderEntryNote], 
		'T2-1' as [ProductCategory], 
		'T2-1' as [ProductGrouping], 
		'1' as [ProductStatus], 
		'T2-1' as [ProductType], 
		1.1 as [ProposedCost], 
		'T2-1' as [PurchasingGroup],
		'T2-1' as [QaInsReason],
		'T2-1' as [SpecialNotes],
		'1' as [Units], 
		'1' as [WarehouseProgram], 
		'1' as [WhiteLabel],
		'T2-1' as [NewCategory], 
		'T2-1' as [SerialRequired], 
		'T2-1' as [Style], 
		'T2-1' as [Size1], 
		'T2-1' as [CurrentLot], 
		1.1 as [UnitSales3Months], 
		1.1 as [UnitSales6Months], 
		1.1 as [UnitSales12Months], 
		'T2-1' as [ProductNumber], 
		'T2-1' as [BodyFabric], 
		'T2-1' as [CushionFillType], 
		'T2-1' as [CushionConfig], 
		'T2-1' as [NailheadFinish], 
		'T2-1' as [NailheadPattern], 
		'T2-1' as [Finish], 
		1.1 as [CustomWidth], 
		1.1 as [CustomDepth], 
		'T2-1' as [CustomArm], 
		'T2-1' as [CustomBack], 
		'T2-1' as [CustomBase], 
		1.1 as [OutboundVolume], 
		1.1 as [UmbHoleDiameter], 
		'T2-1' as [PriceMultiplierCat], 
		'1' as [CustomStockCode], 
		'T2-1' as [WindowBoxFabric], 
		'T2-1' as [SkirtTapingFabric], 
		'T2-1' as [BodyWelt], 
		'T2-1' as [ExtWarrantyType], 
		'T2-1' as [PimDepartment], 
		'T2-1' as [PimCategory], 
		'T2-1' as [PimSubcategory], 
		'T2-1' as [PimType], 
		'T2-1' as [PillowFabric], 
		'T2-1' as [PillowTrim], 
		'T2-1' as [PillowTreatment], 
		'T2-1' as [SkirtTaping], 
		'T2-1' as [SectionalNotches], 
		'T2-1' as [ContrastWeltFabric], 
		'T2-1' as [ContrastWeltLoc], 
		'T2-1' as [ContrastFabric], 
		'T2-1' as [ContrastFabricLoc], 
		'T2-1' as [PimTypeId], 
		'T2-1' as [ContrastInsideFab], 
		'T2-1' as [CushThreadColor], 
		'1' as [OutboundInspection], 
		'1' as [ExcessInventory], 
		'T2-1' as [LabelColor] 

select top 2
	*
from [SysproCompany100_Audit].[Stage].[InvMaster+]
order by Audit_DateTime desc